sudo: required
services:
  - docker

script:
  - docker build -t markwu100/react-example .
  - docker images markwu100/react-example

before_deploy:
  - docker login -u markwu100 -p qiaqia0207

deploy:
  provider: script
  script: docker push markwu100/react-example
  on:
    branch: master